Backend: Quartus
ClockPeriod: 5
HLSConfig:
  LayerName:
    q_dense_429:
      Precision:
        bias: ap_fixed<15,4>
        weight: ap_fixed<15,4>
      ReuseFactor: 1
    q_dense_429_input:
      Precision:
        result: ap_fixed<16,6>
    q_dense_430:
      Precision:
        bias: ap_fixed<15,4>
        weight: ap_fixed<15,4>
      ReuseFactor: 1
    q_dense_431:
      Precision:
        bias: ap_fixed<15,4>
        weight: ap_fixed<15,4>
      ReuseFactor: 1
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'models/hls_models/keras_model.h5'
OutputDir: models/hls_models
OutputPredictions: null
Part: 1SG280HU2F50E2VG
ProjectName: myproject
Stamp: 8e45BC5D
