Backend: Quartus
ClockPeriod: 5
HLSConfig:
  LayerName:
    dense:
      Precision:
        bias: ac_fixed<36,6>
        result: ac_fixed<36,6>
        weight: ac_fixed<36,6>
      ReuseFactor: 1
    dense_1:
      Precision:
        bias: ac_fixed<36,6>
        result: ac_fixed<36,6>
        weight: ac_fixed<36,6>
      ReuseFactor: 1
    dense_1_linear:
      Precision: ac_fixed<36,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    dense_input:
      Precision:
        result: ac_fixed<36,6>
    dense_sigmoid:
      Precision: ac_fixed<36,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ac_fixed<36,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'models/hls_models/keras_model.h5'
OutputDir: models/hls_models
OutputPredictions: null
Part: 1SG280HU2F50E2VG
ProjectName: myproject
Stamp: 17e530be
