Backend: Quartus
ClockPeriod: 5
HLSConfig:
  LayerName:
    q_dense_402:
      Precision:
        bias: ap_fixed<15,4>
        weight: ap_fixed<15,4>
      ReuseFactor: 1
    q_dense_402_input:
      Precision:
        result: ap_fixed<16,6>
    q_dense_403:
      Precision:
        bias: ap_fixed<15,4>
        weight: ap_fixed<15,4>
      ReuseFactor: 1
    q_dense_404:
      Precision:
        bias: ap_fixed<15,4>
        weight: ap_fixed<15,4>
      ReuseFactor: 1
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'models/hls_models/keras_model.h5'
OutputDir: models/hls_models
OutputPredictions: null
Part: 1SG280HU2F50E2VG
ProjectName: myproject
Stamp: c83D932c
