Backend: Quartus
ClockPeriod: 5
HLSConfig:
  LayerName:
    dense:
      Precision:
        bias: ap_fixed<4,4>
        result: ap_fixed<16,6>
        weight: ap_fixed<4,4>
      ReuseFactor: 1
    dense_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    simple_rnn:
      Precision:
        bias: ap_fixed<4,4>
        weight: ap_fixed<4,4>
    simple_rnn_input:
      Precision:
        result: ap_fixed<16,6>
    simple_rnn_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'models/hls_models/keras_model.h5'
OutputDir: models/hls_models
OutputPredictions: null
Part: 1SG280HU2F50E2VG
ProjectName: myproject
Stamp: 741C1cfA
